"""
PDF generation utility for HR reports
"""
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from datetime import datetime
import json
from io import BytesIO


class PDFReportGenerator:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self.setup_custom_styles()
    
    def setup_custom_styles(self):
        """Setup custom styles for the PDF"""
        # Title style
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Title'],
            fontSize=24,
            spaceAfter=30,
            textColor=colors.darkblue,
            alignment=TA_CENTER
        ))
        
        # Subtitle style
        self.styles.add(ParagraphStyle(
            name='CustomSubtitle',
            parent=self.styles['Heading1'],
            fontSize=16,
            spaceAfter=12,
            textColor=colors.darkblue
        ))
        
        # Normal style with better spacing
        self.styles.add(ParagraphStyle(
            name='CustomNormal',
            parent=self.styles['Normal'],
            fontSize=10,
            spaceAfter=6,
            leading=14
        ))
        
        # Header style
        self.styles.add(ParagraphStyle(
            name='CustomHeader',
            parent=self.styles['Heading2'],
            fontSize=14,
            spaceAfter=8,
            textColor=colors.darkblue,
            borderWidth=0,
            borderBottomWidth=1,
            borderColor=colors.lightgrey
        ))
    
    def generate_report_pdf(self, report_data, report_type, filename=None):
        """Generate PDF for any report type"""
        # Use BytesIO to create PDF in memory
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
        story = []
        
        # Report header
        story.append(Paragraph("TalentFlow Pro - HR Report", self.styles['CustomTitle']))
        story.append(Spacer(1, 12))
        
        # Report metadata
        metadata = [
            ['Report Type:', report_type.replace('_', ' ').title()],
            ['Generated:', datetime.now().strftime('%B %d, %Y at %I:%M %p')],
            ['Generated By:', report_data.get('generated_by', 'HR System')],
        ]
        
        if report_data.get('start_date'):
            metadata.append(['Period Start:', report_data['start_date']])
        if report_data.get('end_date'):
            metadata.append(['Period End:', report_data['end_date']])
        
        metadata_table = Table(metadata, colWidths=[2*inch, 4*inch])
        metadata_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.lightgrey),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        story.append(metadata_table)
        story.append(Spacer(1, 20))
        
        # Generate report-specific content
        if report_type == "applications":
            story.extend(self._generate_applications_report(report_data))
        elif report_type == "interviews":
            story.extend(self._generate_interviews_report(report_data))
        elif report_type == "comprehensive":
            story.extend(self._generate_comprehensive_report(report_data))
        elif report_type == "offers":
            story.extend(self._generate_offers_report(report_data))
        elif report_type == "evaluations":
            story.extend(self._generate_evaluations_report(report_data))
        else:
            story.extend(self._generate_generic_report(report_data, report_type))
        
        # Footer
        story.append(Spacer(1, 20))
        story.append(Paragraph("Generated by TalentFlow Pro HR System", self.styles['CustomNormal']))
        
        doc.build(story)
        
        # Get PDF bytes
        pdf_bytes = buffer.getvalue()
        buffer.close()
        
        return pdf_bytes
    
    def _generate_applications_report(self, data):
        """Generate applications report content"""
        story = []
        
        story.append(Paragraph("Applications Report", self.styles['CustomSubtitle']))
        
        # Summary statistics
        if 'statistics' in data:
            stats = data['statistics']
            summary_data = [
                ['Metric', 'Value'],
                ['Total Applicants', str(stats.get('total_applicants', 0))],
                ['Scored Applicants', str(stats.get('scored_applicants', 0))],
                ['Average Score', str(stats.get('average_score', 0))],
            ]
            
            summary_table = Table(summary_data, colWidths=[3*inch, 2*inch])
            summary_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            story.append(summary_table)
            story.append(Spacer(1, 20))
        
        # Score distribution
        if 'statistics' in data and 'score_distribution' in data['statistics']:
            story.append(Paragraph("Score Distribution", self.styles['CustomHeader']))
            
            dist = data['statistics']['score_distribution']
            dist_data = [['Category', 'Count']]
            for category, count in dist.items():
                dist_data.append([category.title(), str(count)])
            
            dist_table = Table(dist_data, colWidths=[3*inch, 2*inch])
            dist_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.darkblue),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            story.append(dist_table)
        
        return story
    
    def _generate_interviews_report(self, data):
        """Generate interviews report content"""
        story = []
        
        story.append(Paragraph("Interviews Report", self.styles['CustomSubtitle']))
        story.append(Paragraph("Total Interviews: " + str(data.get('total_interviews', 0)), self.styles['CustomNormal']))
        
        if 'completion_rates' in data:
            story.append(Paragraph("Interview Completion Rates", self.styles['CustomHeader']))
            rates = data['completion_rates']
            for rate_type, rate_value in rates.items():
                story.append(Paragraph(f"{rate_type.replace('_', ' ').title()}: {rate_value}%", self.styles['CustomNormal']))
        
        return story
    
    def _generate_comprehensive_report(self, data):
        """Generate comprehensive report content"""
        story = []
        
        story.append(Paragraph("Comprehensive HR Report", self.styles['CustomSubtitle']))
        
        # Applications summary
        if 'applications' in data:
            story.append(Paragraph("Applications Summary", self.styles['CustomHeader']))
            story.append(Paragraph(f"Total Applications: {data['applications']}", self.styles['CustomNormal']))
        
        # Statistics
        if 'statistics' in data:
            story.append(Paragraph("Overall Statistics", self.styles['CustomHeader']))
            stats = data['statistics']
            for key, value in stats.items():
                if isinstance(value, (int, float)):
                    story.append(Paragraph(f"{key.replace('_', ' ').title()}: {value}", self.styles['CustomNormal']))
        
        # Hiring pipeline
        if 'hiring_pipeline' in data:
            story.append(Paragraph("Hiring Pipeline", self.styles['CustomHeader']))
            pipeline = data['hiring_pipeline']
            for stage, count in pipeline.items():
                story.append(Paragraph(f"{stage.replace('_', ' ').title()}: {count}", self.styles['CustomNormal']))
        
        return story
    
    def _generate_offers_report(self, data):
        """Generate offers report content"""
        story = []
        
        story.append(Paragraph("Job Offers Report", self.styles['CustomSubtitle']))
        story.append(Paragraph("Total Offers: " + str(data.get('total_offers', 0)), self.styles['CustomNormal']))
        
        if 'offer_status_breakdown' in data:
            story.append(Paragraph("Offer Status Breakdown", self.styles['CustomHeader']))
            breakdown = data['offer_status_breakdown']
            for status, count in breakdown.items():
                story.append(Paragraph(f"{status.title()}: {count}", self.styles['CustomNormal']))
        
        return story
    
    def _generate_evaluations_report(self, data):
        """Generate evaluations report content"""
        story = []
        
        story.append(Paragraph("Candidate Evaluations Report", self.styles['CustomSubtitle']))
        story.append(Paragraph("Total Evaluations: " + str(data.get('total_evaluations', 0)), self.styles['CustomNormal']))
        
        if 'average_scores' in data:
            story.append(Paragraph("Average Scores", self.styles['CustomHeader']))
            scores = data['average_scores']
            for category, score in scores.items():
                story.append(Paragraph(f"{category.replace('_', ' ').title()}: {score}/10", self.styles['CustomNormal']))
        
        return story
    
    def _generate_generic_report(self, data, report_type):
        """Generate generic report content for unknown report types"""
        story = []
        
        story.append(Paragraph(f"{report_type.replace('_', ' ').title()} Report", self.styles['CustomSubtitle']))
        
        # Try to display data in a readable format
        if isinstance(data, dict):
            for key, value in data.items():
                if key not in ['generated_by', 'start_date', 'end_date']:  # Skip metadata already shown
                    if isinstance(value, dict):
                        story.append(Paragraph(f"{key.replace('_', ' ').title()}:", self.styles['CustomHeader']))
                        for sub_key, sub_value in value.items():
                            story.append(Paragraph(f"  {sub_key}: {sub_value}", self.styles['CustomNormal']))
                    else:
                        story.append(Paragraph(f"{key.replace('_', ' ').title()}: {value}", self.styles['CustomNormal']))
        
        return story


def generate_pdf_report(report_data, report_type, filename=None):
    """Convenience function to generate PDF report"""
    generator = PDFReportGenerator()
    return generator.generate_report_pdf(report_data, report_type, filename)
